/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pappu_com_ndkproject_MainActivity */

#ifndef _Included_pappu_com_ndkproject_MainActivity
#define _Included_pappu_com_ndkproject_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pappu_com_ndkproject_MainActivity
 * Method:    messageFromNativeCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pappu_com_ndkproject_MainActivity_messageFromNativeCode
  (JNIEnv *, jobject);

/*
 * Class:     pappu_com_ndkproject_MainActivity
 * Method:    getAverage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pappu_com_ndkproject_MainActivity_getAverage
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
