/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pappu_com_ndkproject_NativeClass */

#ifndef _Included_pappu_com_ndkproject_NativeClass
#define _Included_pappu_com_ndkproject_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pappu_com_ndkproject_NativeClass
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pappu_com_ndkproject_NativeClass_getName
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
